# Tensor flow

In [1]:
import tensorflow as tf
import numpy as np

In [12]:
A = tf.constant([1,2,3])
B = tf.Variable([1,2,3])
print(A)
print(B)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>


In [9]:
C = A.numpy()
print(C)

[1 2 3]


In [6]:
D = tf.ones((2,3), dtype =tf.float32)
print(D)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [7]:
E = tf.eye(3)
print(E)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
F = tf.cast(A, tf.float64)  #change data type
print(F)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [23]:
A = tf.constant([[1,2],[3,4]],dtype=tf.float32)
print(A * A)  # element wise
print(A @ A)  # matrix multiplication 

tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)


In [26]:
print(tf.linalg.det(A))
vl,vt = tf.linalg.eig(A)
print(vl,vt)

tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor([-0.37228122+0.j  5.372281  +0.j], shape=(2,), dtype=complex64) tf.Tensor(
[[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]], shape=(2, 2), dtype=complex64)


# AutoDifferentiation 

In [27]:
x = tf.Variable(1.0) 

with tf.GradientTape() as t:
     y = x**2 + 2*x + 1
        
dy_dx = t.gradient(y,x) 
print(dy_dx)

tf.Tensor(4.0, shape=(), dtype=float32)


In [29]:
x = tf.constant(1.0)  

with tf.GradientTape() as t:
     y = x**2 + 2*x + 1
        
dy_dx = t.gradient(y,x) 
print(dy_dx)

None


In [31]:
x = tf.constant(1.0)

with tf.GradientTape() as t:
    t.watch(x)  #if want to diff respect to "constant" 
    y = x**2 + 2*x + 1
        
dy_dx = t.gradient(y,x) 
print(dy_dx)

tf.Tensor(4.0, shape=(), dtype=float32)


In [33]:
# second derivative
x = tf.Variable(1.0) 

with tf.GradientTape(persistent=True) as t:
    y = x**2
    z = y**2
        
dy_dx = t.gradient(y,x) 
print(dy_dx)
dz_dx = t.gradient(z,x) 
print(dz_dx)

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


In [36]:
def f(x):
    if x < -3:
        return 0.1*x
    if -3<=x<=2:
        return 0.5*x+1.2
    if x>2:
        return 0.1*x+2
    
def df(x):
    with tf.GradientTape() as t:
        y = f(x)
    return t.gradient(y,x)

In [42]:
print(df(tf.Variable(-4.)).numpy())
print(df(tf.Variable(1.)).numpy())
print(df(tf.Variable(2.)).numpy())
print(df(tf.Variable(3.)).numpy())

0.1
0.5
0.5
0.1


In [ ]:
'''
for unconected function
we can give the value to be zero
'''
t.gradient(y,x, unconnected_gradients=tf.UnconnectedGradients.ZERO)